#! /bin/sh

# FUNCTION TO DISPLAY ERROR AND QUIT
__error() {
  echo "NOPE: ${@}"
  echo
  exit 1
}

# CHECK USER WITH whoami(1)
[ "$( whoami )" = "root" ] || __error "run '$( basename ${0} )' as root user"

# SETTINGS
PREFIX="verbsd"
VER="14.0-RELEASE"
ARCH="amd64"
TREE="releases"
LINK="http://ftp.freebsd.org/pub/FreeBSD/${TREE}/${ARCH}/${VER}"
BE="${PREFIX}-${VER}"
BEDIR="/var/tmp/${BE}"
BASEDIR="/jail/BASE"
DISTLIST="base kernel lib32 src"
POOL="zroot"
THEUSER="vuk"
THEUSERUID="1000"
THEUSERDIR="/home/${THEUSER}"
THEUSERGRP="wheel,operator,video,network,webcamd,cups"

PACKAGES="
accessibility/redshift
archivers/7-zip
archivers/cabextract
archivers/engrampa
archivers/gtar
archivers/innoextract
archivers/unrar
archivers/unzip
archivers/zip
audio/audacity
audio/deadbeef
audio/dsbmixer
audio/id3v2
audio/lame
audio/moc
audio/mpg123
audio/mpg321
audio/sayonara
audio/virtual_oss_ctl
benchmarks/blogbench
converters/dosunix
deskutils/clipit
deskutils/foliate
deskutils/gcal
deskutils/xchm
devel/ccache
devel/dbus
devel/dconf-editor
devel/delta
devel/fuzzylite
devel/geany
devel/gettext
devel/glib20
devel/gmake
devel/libublio
devel/ncurses
dns/dnsmasq
editors/leafpad
editors/libreoffice
editors/micro
editors/vim
ftp/filezilla
ftp/gftp
ftp/lftp
ftp/wget
games/cmatrix
games/ctris
games/lolcat
graphics/atril
graphics/djview4
graphics/djvulibre
graphics/drm-kmod
graphics/feh
graphics/fusefs-gphotofs
graphics/gimp
graphics/GraphicsMagick
graphics/jhead
graphics/mupdf
graphics/pngcrush
graphics/scrot
graphics/upscaler
graphics/viewnior
graphics/xournal
irc/irssi
japanese/gawk
japanese/w3m
lang/python
mail/thunderbird
math/galculator
misc/findutils
misc/img2xterm
misc/mbuffer
misc/nnn
misc/qt5ct
misc/shc
misc/unclutter
misc/vifm
multimedia/ffmpeg
multimedia/libva-intel-driver
multimedia/libva-utils
multimedia/libvdpau-va-gl
multimedia/mkvtoolnix
multimedia/mpv
multimedia/pwcview
multimedia/recordmydesktop
multimedia/v4l_compat
multimedia/v4l-utils
multimedia/webcamd
net-mgmt/iftop
net-mgmt/ipcalc
net/arping
net/dhcping
net/gitup
net/ifstat
net/liferea
net/mtr-nox11
net/ngrep
net/rdesktop
net/rsync
net/speedtest-go
net/tigervnc-server
net/tigervnc-viewer
ports-mgmt/dialog4ports
ports-mgmt/pkg
ports-mgmt/pkg_tree
ports-mgmt/portmaster
print/cups
print/pdfarranger
print/pdftk
print/psutils
print/splix
security/clusterssh
security/doas
security/keepassxc
security/nmap
security/sshpass
security/sudo
security/veracrypt
security/wpa_supplicant
shells/zsh
shells/zsh-autosuggestions
shells/zsh-completions
shells/zsh-syntax-highlighting
sysutils/archivemount
sysutils/automount
sysutils/beadm
sysutils/bfs
sysutils/bhyve-firmware
sysutils/bsdinfo
sysutils/ccd2iso
sysutils/cdrdao
sysutils/cdrtools
sysutils/checkrestart
sysutils/coreutils
sysutils/cpufetch
sysutils/daemontools
sysutils/darling-dmg
sysutils/debootstrap
sysutils/detox
sysutils/dmg2img
sysutils/dmidecode
sysutils/dsbwrtsysctl
sysutils/duf
sysutils/dvd+rw-tools
sysutils/e2fsprogs
sysutils/exa
sysutils/exfat-utils
sysutils/freecolor
sysutils/fusefs-exfat
sysutils/fusefs-ext2
sysutils/fusefs-hfsfuse
sysutils/fusefs-jmtpfs
sysutils/fusefs-libs
sysutils/fusefs-lkl
sysutils/fusefs-ntfs
sysutils/fusefs-ntfs-compression
sysutils/fusefs-s3fs
sysutils/fusefs-simple-mtpfs
sysutils/fusefs-sshfs
sysutils/fusefs-zip
sysutils/grub2-bhyve
sysutils/htop
sysutils/hwstat
sysutils/intel-pcm
sysutils/inxi
sysutils/ipmitool
sysutils/lsblk
sysutils/lscpu
sysutils/lsd
sysutils/lsof
sysutils/mdf2iso
sysutils/moreutils
sysutils/ncdu
sysutils/neofetch
sysutils/parallel
sysutils/pciutils
sysutils/powerdxx
sysutils/powermon
sysutils/pstree
sysutils/pv
sysutils/reptyr
sysutils/screen
sysutils/shuf
sysutils/smartmontools
sysutils/tmux
sysutils/turbostat
sysutils/uif2iso
sysutils/usbutils
sysutils/vm-bhyve-devel
sysutils/xorriso
sysutils/zfs-stats
textproc/bat
textproc/docbook-xsl
textproc/docbook2mdoc
textproc/fzf
textproc/gsed
textproc/html2text
textproc/jq
textproc/pdfgrep
textproc/sgrep
textproc/xmlcatmgr
www/aria2
www/chromium
www/firefox
www/links
www/midori
www/tor-browser
net-p2p/transmission
www/yt-dlp
x11-drivers/xf86-input-synaptics
x11-drivers/xf86-video-intel
x11-fm/caja
x11-fm/thunar
x11-fm/xfe
x11-fonts/xfontsel
x11-themes/adwaita-qt5
x11-themes/cursor-dmz-theme
x11-themes/gnome-icons-faenza
x11-themes/gnome-themes-extra
x11-themes/gtk-arc-themes
x11-themes/gtk-murrine-engine
x11-themes/lxappearance
x11-themes/qtcurve-qt5
x11-themes/qtcurve-utils
x11-wm/openbox
x11-wm/picom
x11-wm/skippy-xd
x11/arandr
x11/cool-retro-term
x11/dmenu
x11/dzen2
x11/gxkb
x11/lupe
x11/plank
x11/rofi
x11/rxvt-unicode
x11/sakura
x11/tint
x11/virtualgl
x11/wmctrl
x11/xautolock
x11/xbindkeys
x11/xcb
x11/xcb-util-wm
x11/xclip
x11/xdm
x11/xdotool
x11/xfce4-taskmanager
x11/xlockmore
x11/xorg
x11/xxkb
x11/zenity"
